﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.LightGbm;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace Maskan
{
    public partial class MLModel
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"type", @"type"),new InputOutputColumnPair(@"area", @"area"),new InputOutputColumnPair(@"bedrooms", @"bedrooms"),new InputOutputColumnPair(@"bathrooms", @"bathrooms"),new InputOutputColumnPair(@"region", @"region")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"type",@"area",@"bedrooms",@"bathrooms",@"region"}))      
                                    .Append(mlContext.Regression.Trainers.LightGbm(new LightGbmRegressionTrainer.Options(){NumberOfLeaves=12252,MinimumExampleCountPerLeaf=51,NumberOfIterations=21,MaximumBinCountPerFeature=1024,LearningRate=0.683795244608875F,LabelColumnName=@"price",FeatureColumnName=@"Features",Booster=new GradientBooster.Options(){SubsampleFraction=0.595814679225428F,FeatureFraction=0.01F,L1Regularization=4402875806.21748F,L2Regularization=4.02652943942594E-06F}}));

            return pipeline;
        }
    }
}
