﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace Maskan
{
    public partial class MLModel1
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"type", @"type"),new InputOutputColumnPair(@"area", @"area"),new InputOutputColumnPair(@"bedrooms", @"bedrooms"),new InputOutputColumnPair(@"bathrooms", @"bathrooms"),new InputOutputColumnPair(@"level", @"level"),new InputOutputColumnPair(@"furnished", @"furnished"),new InputOutputColumnPair(@"rent", @"rent"),new InputOutputColumnPair(@"region", @"region")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"type",@"area",@"bedrooms",@"bathrooms",@"level",@"furnished",@"rent",@"region"}))      
                                    .Append(mlContext.Regression.Trainers.FastTree(new FastTreeRegressionTrainer.Options(){NumberOfLeaves=208,MinimumExampleCountPerLeaf=52,NumberOfTrees=9799,MaximumBinCountPerFeature=1024,LearningRate=8.91687071336519E-05F,FeatureFraction=0.574874218182646F,LabelColumnName=@"price",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
